server:
  port: 8088
spring:
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**

  freemarker:
    cache: false    #页面不加载缓存，修改即时生效
  http:
    multipart:
      maxFileSize: 10Mb
      maxRequestSize: 100Mb
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://rm-wz9e0163453eu84559o.mysql.rds.aliyuncs.com:3306/myhis
    username: his
    password: Yxj990407
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    #database-platform: org.hibernate.dialect.Oracle10Dialect
    databse: mysql

mybatis:
  mapper-locations: classpath*:mappers/*.xml
  type-aliases-package: cn.gson.prohis.model.pojos
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
